// Generated by lua5.1.js-file-packer
(function(Lua5_1) {
Lua5_1.provide_file("/pub/lua/", "mymodule.lua",
 "local M = {}\n"
+"function M.printh1(s)\n"
+"print('<h1>'..s..'</h1>')\n"
+"end\n"
+"return M\n",
true, false);
// End of /mymodule.lua
})(Lua5_1);